### https://learn.microsoft.com/ja-jp/training/paths/pytorch-fundamentals/

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]], dtype=torch.int32) 



In [4]:
tensor = torch.rand(3, 4)
print(f"tensor\t{tensor}")
print(f"shape\t{tensor.shape}")
print(f"Device tensor is stored on\t{tensor.device}")

tensor	tensor([[0.2260, 0.4006, 0.3429, 0.6670],
        [0.6893, 0.0587, 0.6871, 0.3385],
        [0.2451, 0.3966, 0.3062, 0.7373]])
shape	torch.Size([3, 4])
Device tensor is stored on	cpu
